### PR TITLE
Milestone 1 - Tic Tac Toe

### PR DESCRIPTION
**Pull request by expjazz**
## We checked all the requirements needed for the next step.

- lib - for the game logic (HINT: as this directory is empty you can use .gitkeep file)
- bin - with the [executable file] https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) called main.rb.
- 
Screenshot from 2020-04-27 05-10-24
main.rb file should be responsible for user interaction. This is the only one place where puts and get.chomp can be used.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Great work :+1: 
Just a few changes required:
* [ ] Stickler is not checking this Pull Request, make sure you set it up correctly. `.stickler.yml` file should have the next content:
```
# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config
# find full documentation here: https://stickler-ci.com/docs
```
* [x] Please kindly delete `bin` file from `bin` directory.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by expjazz** [comment]
## We made all the requested changes
- We made sure that the linter is on.
- We deleted the bin file that was there.
- Thanks @pelzolga123 for the review.

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @expjazz and @frankopkusianwar  :balloon: :lollipop: 

### Thank you for doing all the changes requested by the previous reviewer, :medal_sports:  you may merge this branch and move on :tada: :tada: :tada: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
